// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzBMKpJ9c2N8-8C1VeQUNXhuTCEq00p10',
    appId: '1:460130532750:web:7bb352ab5cdf95c494f8df',
    messagingSenderId: '460130532750',
    projectId: 'ta3lem-3bbd6',
    authDomain: 'ta3lem-3bbd6.firebaseapp.com',
    storageBucket: 'ta3lem-3bbd6.firebasestorage.app',
    measurementId: 'G-1VE939WHNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_XSk9DaWg29OMoWYhPLrOYmIGKxDTreg',
    appId: '1:460130532750:android:6a21c26893f601e994f8df',
    messagingSenderId: '460130532750',
    projectId: 'ta3lem-3bbd6',
    storageBucket: 'ta3lem-3bbd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ4WCNKiCHTNrSb6AkWsErrgppSMpbZ8c',
    appId: '1:460130532750:ios:f142a2e13392923894f8df',
    messagingSenderId: '460130532750',
    projectId: 'ta3lem-3bbd6',
    storageBucket: 'ta3lem-3bbd6.firebasestorage.app',
    iosBundleId: 'com.ta3lem.ta3lemApp',
  );
}
